### ISSUE TITLE
Copy and Excel button are masked.

### ISSUE THREAD

**Issue by wildintellect** [ucdavis/Purchasing#268]
In Chromium, and Firefox on Ubuntu (Linux), if I look at the order history the Copy and Excel buttons are masked by a blank box. In Chromium I can close this box (x in the corner appears on hover) and the then the real buttons are visible but not usable. In Firefox there's no workaround. Chrome appears to work as expected.

**Comment by jSylvestre** [comment]
We don't developer or test on Linux. As there is a workaround, I'm closing this issue unless you want to put in a PR for us to review.
