### ISSUE TITLE
Default to TLS 1.2 (or 1.1 if you have to)

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Purchasing#381]
@jSylvestre same thing we do i think with giving and others, plus we might have to make this change on ACE some in the future.  It's a one-line change in the startup file.  Something to do in the future when we have some time, no rush

**Comment by jSylvestre** [comment]
https://github.com/ucdavis/Commencement/pull/163/commits/8c0723a5760d84635e50756144136d9262f65535
