### ISSUE TITLE
User reports autocomplete of date needed

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Purchasing#425]
I can't reproduce it.

![image](https://user-images.githubusercontent.com/469010/93917667-243b2e00-fcc0-11ea-9fc5-20ebda94d1ab.png)

**Comment by srkirkland** [comment]
It does the same thing for me 
![image](https://user-images.githubusercontent.com/202753/93917807-4df45500-fcc0-11ea-8330-27577e724315.png)
