### ISSUE TITLE
Approval Notifications

### ISSUE THREAD

**Issue by rsynnest** [ucdavis/Purchasing#442]
I just had a scenario where the Conditional Approver denied an order because they thought the Initial Approver had already approved the first Approval stage, and there were requirements missing from that first stage. The Conditional Approver thought (as did I) that they would only be notified of an order once the initial Approver stage was complete, and they didn't check whether the Approval Status for the first Approver was complete (it was still "Pending").

This could just be user oversight, and I don't know the exact behavior or email content since I'm not an approver, but maybe the email notifications aren't super clear? My thinking is it would make sense to notify all approvers when an order is created, and show clearly that the notification is for an "Order Created" event. Then maybe notify each Approver when the previous approval stage is complete - maybe an "Approval Required" notification (or other important events?). Maybe this is already the case, I don't know since I can't test it as an approver, but if not, I think it would be a useful feature to add.

**Comment by jSylvestre** [comment]
Please do not put issues in this repository directly.
If you like you can submit a help ticket from within help and I'll follow up with you there.
