### ISSUE TITLE
Order export date not formatted properly

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Purchasing#547]
On the order history page, if you export the data it makes all the date fields really funny by prepending a unix timestamp to the fields.  So you date column is `63806802803927000012/16/2022` for example.  This was changed 6mo ago https://github.com/ucdavis/Purchasing/blame/81c0e01873e60cf2645a3974200e566c3fc83b6c/Purchasing.Mvc/Views/History/_OrdersTable.cshtml#L229.

Not sure why data tables can't sort by date w/o the timestamp (it can in other projects) but there is probably more than meets the eye to this issue.  Either way, let's try to fix.

**Comment by jSylvestre** [comment]
Need to change them to:
result.Append("<td data-sort=\"" + @item.DateCreated.Ticks + "\">" + String.Format("{0:d}", item.DateCreated) + "</td>");
